before_script:
  - npm ci --ignore-scripts --force

build:
  stage: build
  script: npm run build
  only:
    - merge_requests

lint:
  stage: test
  script: npm run lint
  only:
    - merge_requests

test:
  stage: test
  script: npm run test
  only:
    - merge_requests
