import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettierConfig from 'eslint-config-prettier';

export default [
    {
        ignores: ['dist/**', 'node_modules/**'],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    prettierConfig,
    {
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
        },
        rules: {
            '@typescript-eslint/no-non-null-assertion': 'off',
            '@typescript-eslint/no-explicit-any': 'off',
            'no-constant-condition': ['error', { checkLoops: false }],
            'no-control-regex': 'off',
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-prototype-builtins': 'off',
            'no-shadow': 'error',
            'no-useless-backreference': 'error',
            'array-callback-return': 'error',
            'consistent-return': 'error',
            'curly': 'error',
            'default-case-last': 'error',
            'dot-notation': 'error',
            'eqeqeq': ['error', 'always', { null: 'ignore' }],
            'no-caller': 'error',
            'no-eval': 'error',
            'no-extra-bind': 'error',
            'no-floating-decimal': 'error',
            'no-implied-eval': 'error',
            'no-implicit-globals': 'error',
            'no-lone-blocks': 'error',
            'no-loop-func': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-octal-escape': 'error',
            'no-return-assign': 'error',
            'no-script-url': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-throw-literal': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unused-expressions': 'error',
            'no-useless-call': 'error',
            'no-useless-concat': 'error',
            'no-useless-escape': 'off',
            'no-useless-return': 'error',
            'prefer-regex-literals': 'error',
            'radix': 'error',
            'no-label-var': 'error',
            'one-var': ['error', 'never'],
            'one-var-declaration-per-line': 'error',
            'no-var': 'error',
            'prefer-arrow-callback': 'error',
            'prefer-const': 'error',
        },
    },
];
